[project]
name = "intro-to-prefect"
description = "A beginner project for scheduling with Prefect"
version = "0.1.0"

dependencies = [
    "prefect ~= 2.13.2",
    "psycopg2-binary ~= 2.9.7"
]

[project.optional-dependencies]
dev = [
    "pre-commit"
]

